local Prototype = require("pixelfrog.enemies.plant.plant")

local defold = _G

go.property("health_points", 1)
go.property("damage_points", 1)
go.property("horizontal_look", 1)
go.property("bullet_speed", 200)
go.property("bullet_damage_points", 1)
go.property("shots_per_attack", 3)
go.property("activator", hash(""))

function defold.init(self)
   self.instance = Prototype.new(self)
end

function defold.final(self)
   Prototype.free(self.instance)
end
