-- import
local MSG = require("scripts.shared.messages")
local ui = require("scripts.shared.ui.ui")

-- localization
local defold = _G
local post = msg.post
local set_render_order = gui.set_render_order

-- functions
local enable
local disable

---------------------------------------
-- init
---------------------------------------

function defold.init(self)
	ui.startup_background_context = self
	disable()
	set_render_order(6)
  self.enable = enable
  self.disable = disable
end -- init

---------------------------------------
-- final
---------------------------------------

function defold.final()
	ui.startup_background_context = nil
end -- final

---------------------------------------
-- enable
---------------------------------------

function enable()
	post("#", MSG.ENABLE)
end -- enable

---------------------------------------
-- disable
---------------------------------------

function disable ()
	post("#", MSG.DISABLE)
end -- disable
