local Trunk = require("pixelfrog.enemies.trunk.trunk")

local defold = _G

go.property("health_points", 1)
go.property("damage_points", 1)
go.property("horizontal_look", 0)
go.property("bullet_speed", 200)
go.property("bullet_damage_points", 1)
go.property("shots_per_attack", 3)
go.property("activator", hash(""))
go.property("probe_length", 2)

function defold.init(self)
   self.instance = Trunk.new(self)
end

function defold.final(self)
   Trunk.free(self.instance)
end
