local Bluebird = require("pixelfrog.enemies.bluebird.bluebird")

local defold = _G

go.property("health_points", 1)
go.property("damage_points", 1)
go.property("activator", hash(""))

go.property("name", hash(""))
go.property("start_waypoint", 1)
go.property("speed", 0)
go.property("wait_time", 0)
go.property("easing_factor", 1)

function defold.init(self)
   self.instance = Bluebird.new(self)
end

function defold.final(self)
   Bluebird.free(self.instance)
end
