-- import
local LAYER = require("scripts.shared.layers")
-- local utils = require("scripts.shared.utils")

-- localization
local defold = _G
local get_position = go.get_position
local set_position = go.set_position

---------------------------------------
-- init
---------------------------------------
function defold.init()
    local position = get_position()
    position.z = LAYER.TILES_A
    set_position(position)
end
