local SnailShell = require("pixelfrog.enemies.snail.snail_shell.snail_shell")

local defold = _G

go.property("health_points", 1)
go.property("damage_points", 1)
go.property("horizontal_look", 0)
go.property("activator", hash(""))
go.property("initial_rotation", vmath.quat())

function defold.init(self)
   self.instance = SnailShell.new(self)
end

function defold.final(self)
   SnailShell.free(self.instance)
end
