local Prototype = require("pixelfrog.props.pressure_plates.pressure_plate")

local defold = _G

go.property("name", hash(""))
go.property("target_name", hash(""))
go.property("kind", 1) -- 1: big, 2: small
go.property("is_permanent", false)
go.property("acceleration", 2000)
go.property("max_speed", 1000)

function defold.init(self)
   self.instance = Prototype.new(self)
end -- defold.init

function defold.final(self)
   Prototype.free(self.instance)
end -- defold.final
